# Generated by Django 4.0.5 on 2022-06-23 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha'),
        ),
    ]
